# Generated by Django 2.2.14 on 2025-03-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250302_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('O', 'Outfits'), ('SP', 'Sports'), ('E', 'Electronics')], max_length=2),
        ),
    ]
